/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package nc.vista.cliente.dialog;

/**
 *
 * @author nicol
 */
public class CerrarPedido extends javax.swing.JDialog {

    private enum paymentMethod{
        MERCADO_PAGO,
        TRANSFERENCIA
    }
    private paymentMethod metodoPago;
    /**
     * Creates new form CerrarPedido
     * @param parent
     * @param modal
     */
    public CerrarPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mpRadio.setSelected(true);
        hidePayment();
        this.metodoPago = paymentMethod.MERCADO_PAGO;
        this.aliasLabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void hidePayment(){
        this.aliasCBUText.setText("");
        this.cuitText.setText("");
        this.cuitText.setVisible(false);
        this.aliasLabel.setVisible(false);
        this.cbuLabel.setVisible(false);
        this.cuitLabel.setVisible(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        mpRadio = new javax.swing.JRadioButton();
        transferenciaRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuitText = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        aliasCBUText = new javax.swing.JTextPane();
        aliasLabel = new javax.swing.JLabel();
        cbuLabel = new javax.swing.JLabel();
        cuitLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resumeText = new javax.swing.JTextArea();
        cerrarPedidoButton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(mpRadio);
        mpRadio.setText("Mercado Pago");
        mpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpRadioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(mpRadio, gridBagConstraints);

        buttonGroup1.add(transferenciaRadio);
        transferenciaRadio.setText("Transferencia");
        transferenciaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaRadioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(transferenciaRadio, gridBagConstraints);

        jLabel1.setText("Seleccione método de pago");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jScrollPane2.setViewportView(cuitText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jScrollPane3.setViewportView(aliasCBUText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        aliasLabel.setText("Alias: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(aliasLabel, gridBagConstraints);

        cbuLabel.setText("CBU: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(cbuLabel, gridBagConstraints);

        cuitLabel.setText("CUIT:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(cuitLabel, gridBagConstraints);

        resumeText.setEditable(false);
        resumeText.setColumns(20);
        resumeText.setRows(5);
        jScrollPane4.setViewportView(resumeText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        cerrarPedidoButton.setText("Cerrar Pedido");
        cerrarPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPedidoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cerrarPedidoButton, gridBagConstraints);

        jLabel6.setText("Resumen de su pedido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPedidoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPedidoButtonActionPerformed

    private void mpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpRadioActionPerformed
        hidePayment();
        this.metodoPago = paymentMethod.MERCADO_PAGO;
        this.aliasLabel.setVisible(true);
    }//GEN-LAST:event_mpRadioActionPerformed

    private void transferenciaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaRadioActionPerformed
         hidePayment();
        this.metodoPago = paymentMethod.TRANSFERENCIA;
        this.cbuLabel.setVisible(true);;
        this.cuitLabel.setVisible(true);
        this.cuitText.setVisible(true);
    }//GEN-LAST:event_transferenciaRadioActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane aliasCBUText;
    private javax.swing.JLabel aliasLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cbuLabel;
    private javax.swing.JToggleButton cerrarPedidoButton;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JTextPane cuitText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton mpRadio;
    private javax.swing.JTextArea resumeText;
    private javax.swing.JRadioButton transferenciaRadio;
    // End of variables declaration//GEN-END:variables
}
