/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nc.vista.initView.dialog;

import nc.controlador.VendedorController;
import nc.vista.initView.VendedoresMenuPanel;
import nc.vista.initView.VendedoresMenuPanel;

/**
 *
 * @author jereb
 */
public class CreacionVendedor extends javax.swing.JFrame {

    VendedoresMenuPanel panelSuperior;
    
    public CreacionVendedor(VendedoresMenuPanel panelSuperior) {
        this.panelSuperior=panelSuperior;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtNombre = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtCoordenada = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfCoorX = new javax.swing.JTextField();
        tfCoorY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtNombre.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(txtNombre, gridBagConstraints);

        txtDireccion.setText("Direccion: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(txtDireccion, gridBagConstraints);

        txtCoordenada.setText("Coordenada: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(txtCoordenada, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(btnGuardar, gridBagConstraints);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(Cancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 75;
        getContentPane().add(tfNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 75;
        getContentPane().add(tfDireccion, gridBagConstraints);

        tfCoorX.setText("x:");
        tfCoorX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCoorXFocusGained(evt);
            }
        });
        tfCoorX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCoorXActionPerformed(evt);
            }
        });
        tfCoorX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCoorXKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(tfCoorX, gridBagConstraints);

        tfCoorY.setText("y:");
        tfCoorY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCoorYFocusGained(evt);
            }
        });
        tfCoorY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCoorYActionPerformed(evt);
            }
        });
        tfCoorY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCoorYKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(tfCoorY, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       panelSuperior.crearVendedor(tfNombre.getText(), tfDireccion.getText(), Double.parseDouble(tfCoorX.getText()), Double.parseDouble(tfCoorY.getText()));
       panelSuperior.updateModel();
        dispose();
        /*VendedorController vendedor = new VendedorController();
        vendedor.crear(tfNombre.getText(), tfDireccion.getText(), Double.parseDouble(tfCoorX.getText()), Double.parseDouble(tfCoorY.getText()));
        dispose();*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void tfCoorXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCoorXActionPerformed
      
    }//GEN-LAST:event_tfCoorXActionPerformed

    private void tfCoorYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCoorYActionPerformed
       
    }//GEN-LAST:event_tfCoorYActionPerformed

    private void tfCoorXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCoorXKeyTyped
        char car = evt.getKeyChar();
    if((car < '0' || car > '9') && car != '.') evt.consume();
    }//GEN-LAST:event_tfCoorXKeyTyped

    private void tfCoorYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCoorYKeyTyped
        char car = evt.getKeyChar();
    if((car < '0' || car > '9') && car != '.') evt.consume();
    }//GEN-LAST:event_tfCoorYKeyTyped

    private void tfCoorXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoorXFocusGained
         if (tfCoorX.getText().equals("x:")) {
            tfCoorX.setText("");
        }
    }//GEN-LAST:event_tfCoorXFocusGained

    private void tfCoorYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoorYFocusGained
          if (tfCoorY.getText().equals("y:")) {
            tfCoorY.setText("");
          }
    }//GEN-LAST:event_tfCoorYFocusGained

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField tfCoorX;
    private javax.swing.JTextField tfCoorY;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JLabel txtCoordenada;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
