/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista;

/**
 *
 * @author nicol
 */
public class ClientesFrame extends javax.swing.JPanel {

    /**
     * Creates new form ClientesFrame
     */
    public ClientesFrame() {
        initComponents();
        jTabbedPane1.setEnabledAt(jTabbedPane1.indexOfComponent(itemMenuPanelCliente1), false);
    }
    public void setVendedor(){
        jTabbedPane1.setEnabledAt(jTabbedPane1.indexOfComponent(vendedoresSelectPanelCliente1), false);
        jTabbedPane1.setEnabledAt(jTabbedPane1.indexOfComponent(itemMenuPanelCliente1), true);
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(itemMenuPanelCliente1));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        vendedoresSelectPanelCliente1 = new nc.vista.VendedoresSelectPanelCliente(this);
        itemMenuPanelCliente1 = new nc.vista.ItemMenuPanelCliente();
        itemPedidoPanelCliente1 = new nc.vista.ItemPedidoPanelCliente();
        pedidosMenuPanelCliente1 = new nc.vista.PedidosMenuPanelCliente();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Vendedores", vendedoresSelectPanelCliente1);
        jTabbedPane1.addTab("ItemMenu", itemMenuPanelCliente1);
        jTabbedPane1.addTab("Carrito", itemPedidoPanelCliente1);
        jTabbedPane1.addTab("Pedidos", pedidosMenuPanelCliente1);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nc.vista.ItemMenuPanelCliente itemMenuPanelCliente1;
    private nc.vista.ItemPedidoPanelCliente itemPedidoPanelCliente1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private nc.vista.PedidosMenuPanelCliente pedidosMenuPanelCliente1;
    private nc.vista.VendedoresSelectPanelCliente vendedoresSelectPanelCliente1;
    // End of variables declaration//GEN-END:variables
}
