/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista;

/**
 *
 * @author nicol
 */
public class FirstFrame extends javax.swing.JPanel {

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        vendedoresMenuPanel2 = new nc.vista.VendedoresMenuPanel();
        clientesMenuPanel2 = new nc.vista.ClientesMenuPanel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane3.addTab("Vendedores", vendedoresMenuPanel2);
        jTabbedPane3.addTab("Clientes", clientesMenuPanel2);

        add(jTabbedPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nc.vista.ClientesMenuPanel clientesMenuPanel2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private nc.vista.VendedoresMenuPanel vendedoresMenuPanel2;
    // End of variables declaration//GEN-END:variables
}
