/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista;

import nc.controlador.ItemMenuController;
import nc.modelo.ItemMenuDAOandMemory.ItemMenuMemory;

/**
 *
 * @author nicol
 */
public class ItemMenuPanel extends javax.swing.JPanel {
    private ItemMenuTableModelo modeloItemMenu;
    private ItemMenuController itemsMenu;
    /**
     * Creates new form ItemMenuPanel
     */
    public ItemMenuPanel() {
        itemsMenu = new ItemMenuController(ItemMenuMemory.getInstancia());
        modeloItemMenu = new ItemMenuTableModelo(itemsMenu.loadData());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        contentTable = new javax.swing.JTable();
        jSplitPane5 = new javax.swing.JSplitPane();
        creationButton = new javax.swing.JButton();
        jSplitPane6 = new javax.swing.JSplitPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();

        jPanel7.setLayout(new java.awt.GridBagLayout());

        contentTable.setModel(this.modeloItemMenu);
        contentTable.setCellSelectionEnabled(true);
        contentTable.setRowSorter(new ItemMenuRowSorter(contentTable));
        jScrollPane10.setViewportView(contentTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jScrollPane10, gridBagConstraints);

        creationButton.setText("Crear Nuevo ItemMenu");
        creationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationButtonActionPerformed(evt);
            }
        });
        jSplitPane5.setLeftComponent(creationButton);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(1);
        jTextArea4.setPreferredSize(new java.awt.Dimension(232, 10));
        jScrollPane11.setViewportView(jTextArea4);

        jSplitPane6.setRightComponent(jScrollPane11);

        jTextPane6.setEditable(false);
        jTextPane6.setText("Buscador:");
        jTextPane6.setAutoscrolls(false);
        jTextPane6.setFocusable(false);
        jScrollPane12.setViewportView(jTextPane6);

        jSplitPane6.setLeftComponent(jScrollPane12);

        jSplitPane5.setRightComponent(jSplitPane6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel7.add(jSplitPane5, gridBagConstraints);

        jTextPane3.setEditable(false);
        jTextPane3.setText("Lista de ItemMenu");
        jTextPane3.setToolTipText("");
        jTextPane3.setAutoscrolls(false);
        jTextPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane3.setFocusable(false);
        jScrollPane13.setViewportView(jTextPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel7.add(jScrollPane13, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contentTable;
    private javax.swing.JButton creationButton;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane6;
    // End of variables declaration//GEN-END:variables
}
