/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista;

import java.awt.CardLayout;

/**
 *
 * @author nicol
 */
public class VistaPrincipal extends javax.swing.JPanel {
    enum tipoUsuario{
        CLIENTE,
        VENDEDOR
    }
    /**
     * Creates new form VistaPrincipal
     */
    private CardLayout layout;
    private tipoUsuario usuario = null;
    
    @SuppressWarnings("")
    public VistaPrincipal() {
        initComponents();
        this.firstFrame1.setUpperPanel(this);
        this.vendoresFrame1.setFrameSuperior(this);
        this.clientesFrame1.setFrameSuperior(this);
        this.layout = (CardLayout) this.getLayout();
        layout.show(this, "card2");
        
    }
    
    public void setVendedor(int idVendedor){
        this.usuario = tipoUsuario.VENDEDOR;
        vendoresFrame1.setVendedor(idVendedor);
        layout.show(this, "card3");
    }
    public void setCliente(int idCliente){
        this.usuario = tipoUsuario.CLIENTE;
        this.clientesFrame1.setCliente(idCliente);
        layout.show(this, "card4");
    }
    public void volverInicio(){
        this.usuario = null;
        layout.show(this, "card2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstFrame1 = new nc.vista.initView.FirstFrame();
        vendoresFrame1 = new nc.vista.vendedor.VendoresFrame();
        clientesFrame1 = new nc.vista.cliente.ClientesFrame();

        setLayout(new java.awt.CardLayout());
        add(firstFrame1, "card2");
        add(vendoresFrame1, "card3");
        add(clientesFrame1, "card4");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nc.vista.cliente.ClientesFrame clientesFrame1;
    private nc.vista.initView.FirstFrame firstFrame1;
    private nc.vista.vendedor.VendoresFrame vendoresFrame1;
    // End of variables declaration//GEN-END:variables
}
