/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package nc.vista.cliente;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import nc.controller.ItemMenuController;
import nc.excepciones.PedidoCerradoException;
import nc.excepciones.PedidoIncorrectoException;
import nc.excepciones.VendedorIncorrectoException;
import nc.modelo.ItemMenu;

/**
 *
 * @author jereb
 */
public class AgregarCarrito extends javax.swing.JDialog {

    /**
     * Creates new form AgregarCarrito
     */
    public AgregarCarrito(java.awt.Frame parent, boolean modal,int id, ItemMenuController itemsMenu, ItemMenuPanelCliente panelSup) {
        super(parent, modal);
        initComponents();
        this.items = itemsMenu;
        item = items.getItemMenu(id);
        txtName.setText((String)item.get(1));
        precio = (float)item.get(4);
        superior = panelSup;
    }
    ItemMenuPanelCliente superior;
    List item;
    ItemMenuController items;
    int cantidad;
    String info;
    float precio;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cant = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JLabel();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtName.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 13, 5, 13);
        getContentPane().add(txtName, gridBagConstraints);

        jLabel1.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel1, gridBagConstraints);

        cant.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(cant, gridBagConstraints);

        txtPrecio.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(txtPrecio, gridBagConstraints);

        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(sumar, gridBagConstraints);

        restar.setText("-");
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(restar, gridBagConstraints);

        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(btnGuardar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(btnCancelar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        cantidad = Integer.parseInt(cant.getText())+1;
        info = cantidad+"";
        cant.setText(info);
        info = (precio * cantidad)+"";
        txtPrecio.setText(info);
        
        
    }//GEN-LAST:event_sumarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            superior.agregar(Integer.parseInt(cant.getText()),(int) item.get(0));
            
        //Excepciones
        
        } catch (VendedorIncorrectoException ex) {
            Logger.getLogger(AgregarCarrito.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PedidoIncorrectoException ex) {
            Logger.getLogger(AgregarCarrito.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PedidoCerradoException ex) {
            Logger.getLogger(AgregarCarrito.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        cantidad = Integer.parseInt(cant.getText())-1;
        info = cantidad+"";
        cant.setText(info);
        info = (precio * cantidad)+"";
        txtPrecio.setText(info);
    }//GEN-LAST:event_restarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel cant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton restar;
    private javax.swing.JButton sumar;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPrecio;
    // End of variables declaration//GEN-END:variables
}
