/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista.vendedor;

/**
 *
 * @author nicol
 */
public class VendoresFrame extends javax.swing.JPanel {

    /**
     * Creates new form VendoresFrame
     */
    public VendoresFrame() {
        initComponents();
        jTabbedPane1.setEnabledAt(jTabbedPane1.indexOfComponent(itemPedidoPanel1), false);
    }
    public void setPedido(){
        jTabbedPane1.setEnabledAt(jTabbedPane1.indexOfComponent(itemPedidoPanel1), true);
        //jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(itemPedidoPanel1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        itemMenuPanelVendedor1 = new nc.vista.vendedor.ItemMenuPanelVendedor();
        pedidosMenuPanelVendedor1 = new nc.vista.vendedor.PedidosMenuPanelVendedor(this);
        itemPedidoPanel1 = new nc.vista.vendedor.ItemPedidoPanel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Mi menú", itemMenuPanelVendedor1);
        jTabbedPane1.addTab("Mis Pedidos", pedidosMenuPanelVendedor1);
        jTabbedPane1.addTab("Detalle Pedido", itemPedidoPanel1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nc.vista.vendedor.ItemMenuPanelVendedor itemMenuPanelVendedor1;
    private nc.vista.vendedor.ItemPedidoPanel itemPedidoPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private nc.vista.vendedor.PedidosMenuPanelVendedor pedidosMenuPanelVendedor1;
    // End of variables declaration//GEN-END:variables
}
