/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nc.vista.initView;

import nc.vista.VistaPrincipal;

/**
 *
 * @author nicol
 */
public class FirstFrame extends javax.swing.JPanel {

    /**
     * Creates new form FirstFrame
     */
    public VistaPrincipal upperPanel;
    @SuppressWarnings("")
    public FirstFrame( ) {
        initComponents();
        this.vendedoresMenuPanel1.setUpperPanel(this);
        this.clientesMenuPanel1.setUpperFrame(this);
    }
    public void setUpperPanel(VistaPrincipal upperPanel){
        this.upperPanel = upperPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        vendedoresMenuPanel1 = new nc.vista.initView.VendedoresMenuPanel();
        clientesMenuPanel1 = new nc.vista.initView.ClientesMenuPanel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Vendedores", vendedoresMenuPanel1);
        jTabbedPane1.addTab("Clientes", clientesMenuPanel1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nc.vista.initView.ClientesMenuPanel clientesMenuPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private nc.vista.initView.VendedoresMenuPanel vendedoresMenuPanel1;
    // End of variables declaration//GEN-END:variables
}
